name: tablet_print_station
description: Queue Management - Tablet 1 Print Station
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Core functionality
  mqtt_client: ^10.4.0
  sqflite: ^2.3.3+1
  shared_preferences: ^2.2.3

  # UI/UX
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3

  # Printer & Network integration
  esc_pos_utils: ^1.1.0
  network_info_plus: ^5.0.3

  # Utilities
  intl: ^0.19.0
  path: ^1.9.0
  uuid: ^4.4.0
  connectivity_plus: ^6.0.3
  permission_handler: ^11.3.1

  # QR Code for config sharing
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true